<a href="https://colab.research.google.com/github/apollo13092808/pytorch-tutorial-youtube/blob/main/Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor([1, 2, 3, 4])
t2 = torch.tensor([5, 6, 7, 8])

In [3]:
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([5, 6, 7, 8])


## Addition

In [4]:
print(t1 + t2)

tensor([ 6,  8, 10, 12])


In [5]:
print(torch.add(t1, t2))

tensor([ 6,  8, 10, 12])


In [6]:
print(t1.add(t2))

tensor([ 6,  8, 10, 12])


## Subtraction

In [7]:
print(t2 - t1)

tensor([4, 4, 4, 4])


In [8]:
print(torch.sub(t2, t1))

tensor([4, 4, 4, 4])


In [9]:
print(t2.sub(t1))

tensor([4, 4, 4, 4])


## Multiplication

In [10]:
print(t1 * t2)

tensor([ 5, 12, 21, 32])


In [11]:
print(torch.mul(t1, t2))

tensor([ 5, 12, 21, 32])


In [12]:
print(t1.mul(t2))

tensor([ 5, 12, 21, 32])


## Division

In [13]:
print(t2 / t1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [14]:
print(torch.div(t2, t1))

tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [15]:
print(t2.div(t1))

tensor([5.0000, 3.0000, 2.3333, 2.0000])


## Remainder

In [16]:
print(t2 % t1)

tensor([0, 0, 1, 0])


In [17]:
print(torch.remainder(t2, t1))

tensor([0, 0, 1, 0])


In [18]:
print(t2.remainder(t1))

tensor([0, 0, 1, 0])


## Exponents

In [19]:
print(t1 ** t2)

tensor([    1,    64,  2187, 65536])


In [20]:
print(torch.pow(t1, t2))

tensor([    1,    64,  2187, 65536])


In [21]:
print(t1.pow(t2))

tensor([    1,    64,  2187, 65536])
