<a href="https://colab.research.google.com/github/apollo13092808/pytorch-tutorial-youtube/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t = torch.arange(10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Reshape

In [3]:
t = t.reshape(2, 5)
print(t)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [4]:
t = torch.arange(10)

t = t.reshape(2, -1)
print(t)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [5]:
t = torch.arange(10)

t = t.reshape(-1, 2)
print(t)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


## View

In [6]:
t1 = torch.arange(10)
print(t1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
t2 = t1.view(2, 5)
print(t2)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


## Slices

In [8]:
t = torch.arange(10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
print(t[7])

tensor(7)


In [10]:
print(t[4:])

tensor([4, 5, 6, 7, 8, 9])


In [11]:
t = t.reshape(-1, 2)
print(t)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [12]:
print(t[:, 1:])

tensor([[1],
        [3],
        [5],
        [7],
        [9]])


In [13]:
print(t[:, 1])

tensor([1, 3, 5, 7, 9])
