<a href="https://colab.research.google.com/github/apollo13092808/pytorch-tutorial-youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

## Python Lists

In [2]:
lst = [1, 2, 3, 4, 5]
print(lst)

[1, 2, 3, 4, 5]


In [3]:
lst = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
print(lst)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


## NumPy Arrays

In [4]:
arr = np.random.rand(3, 4)
print(arr)

[[0.51744957 0.8811765  0.60968104 0.9132217 ]
 [0.0069886  0.19523526 0.83851139 0.26428448]
 [0.46940224 0.41092635 0.57642799 0.02662543]]


In [5]:
print(arr.dtype)

float64


## PyTorch Tensors

In [6]:
ts = torch.randn(3, 4)
print(ts)

tensor([[ 0.7765,  0.7535,  0.1806,  0.5858],
        [ 1.3213,  1.6409,  1.6320,  0.7779],
        [ 0.6478, -0.1673,  0.3226, -0.8337]])


In [7]:
print(ts.dtype)

torch.float32


In [8]:
ts = torch.zeros(2, 3, 4)
print(ts)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [9]:
# Create tensor from NumPy array
ts = torch.tensor(arr)
print(ts)

tensor([[0.5174, 0.8812, 0.6097, 0.9132],
        [0.0070, 0.1952, 0.8385, 0.2643],
        [0.4694, 0.4109, 0.5764, 0.0266]], dtype=torch.float64)
